import type pg from 'pg';

type Row = {
  name: string;
  kind: 'table' | 'view';
  columns: string[];
  ledger_source: 'lab_id' | 'ledger_id' | 'company' | null;
  insert_only: boolean;
  door_only: boolean;
};

/**
 * Reads the catalog and writes the table classification the scope plugin and the type split use.
 * A registered table is classed by the ledger source its capture trigger was registered with,
 * which is the same fact the database enforces on writes:
 *   lab      registered with lab_id      -> readable only in a Lab scope, filtered to it
 *   ledger   registered with ledger_id   -> filtered to the scope's ledgers
 *   portal   a view named portal_*       -> the only relations a Customer scope may name
 *   company  everything else             -> readable in any staff scope
 * An unregistered relation with a ledger_id column (the audit trail, the derived views) is a
 * ledger relation. The file also lists which tables are insert-only and which are written only
 * through a door function.
 */
export async function classificationSource(client: pg.Client): Promise<string> {
  const rows = await client.query<Row>(`
    select c.relname as name,
           case c.relkind when 'v' then 'view' else 'table' end as kind,
           array(select a.attname::text from pg_attribute a
                  where a.attrelid = c.oid and a.attnum > 0 and not a.attisdropped order by a.attnum) as columns,
           (select (string_to_array(encode(t.tgargs, 'escape'), '\\000'))[1]
              from pg_trigger t where t.tgrelid = c.oid and t.tgname = 'capture') as ledger_source,
           exists (select 1 from pg_trigger t where t.tgrelid = c.oid and t.tgname = 'block_mutation') as insert_only,
           c.relkind = 'r' and not has_table_privilege('lims_app', c.oid, 'INSERT') as door_only
      from pg_class c join pg_namespace n on n.oid = c.relnamespace
     where n.nspname = 'lims' and c.relkind in ('r', 'v') and c.relname <> 'migration'
     order by c.relname`);
  const lab: string[] = [];
  const ledger: string[] = [];
  const portal: string[] = [];
  const company: string[] = [];
  for (const r of rows.rows) {
    if (r.kind === 'view' && r.name.startsWith('portal_')) portal.push(r.name);
    else if (r.ledger_source === 'lab_id') lab.push(r.name);
    else if (r.ledger_source === 'ledger_id' || (r.ledger_source === null && r.columns.includes('ledger_id'))) ledger.push(r.name);
    else company.push(r.name);
  }
  const insertOnly = rows.rows.filter((r) => r.insert_only).map((r) => r.name);
  const doorOnly = rows.rows.filter((r) => r.door_only && r.kind === 'table').map((r) => r.name);
  const list = (xs: string[]) => `[${xs.map((x) => `'${x}'`).join(', ')}] as const`;
  return `// Generated by scripts/codegen.ts from the migrated database. Do not edit.
export const LAB_TABLES = ${list(lab)};
export const LEDGER_TABLES = ${list(ledger)};
export const PORTAL_VIEWS = ${list(portal)};
export const COMPANY_TABLES = ${list(company)};
export const INSERT_ONLY_TABLES = ${list(insertOnly)};
export const DOOR_ONLY_TABLES = ${list(doorOnly)};

export type LabTable = (typeof LAB_TABLES)[number];
export type LedgerTable = (typeof LEDGER_TABLES)[number];
export type PortalView = (typeof PORTAL_VIEWS)[number];
export type CompanyTable = (typeof COMPANY_TABLES)[number];
`;
}
