packages:
  - packages/*
  - apps/*
minimumReleaseAgeExclude:
  - '@vitest/mocker@5.0.3'
  - '@vitest/spy@5.0.3'
  - pg-cloudflare@1.4.1
  - pg-connection-string@2.14.1
  - pg-protocol@1.16.1
  - pg@8.23.1
  - vitest@5.0.3
