
/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Account {
  disabled_at: Timestamp | null;
  identity_check_method: string | null;
  identity_checked_at: Timestamp | null;
  identity_checked_by: string | null;
  password_hash: string | null;
  person_id: string;
  totp_secret_enc: Buffer | null;
  username: string;
}

export interface Alert {
  at: Generated<Timestamp>;
  detail: Generated<Json>;
  id: Generated<Int8>;
  kind: string;
  person_id: string | null;
  session_id: string | null;
}

export interface AuditChainHead {
  head_hash: Generated<Buffer>;
  head_seq: Generated<Int8>;
  ledger_id: string;
}

export interface AuditEntry {
  acting_lab_id: string | null;
  action: string;
  app_release: string;
  at: Timestamp;
  changes: Json;
  commit_key: string | null;
  customer_id: string | null;
  entry_bytes: Buffer;
  entry_hash: Generated<Buffer>;
  ledger_id: string;
  op: string;
  person_id: string;
  prev_hash: Buffer;
  reason_code: string;
  reason_text: string | null;
  record_id: string | null;
  role: string;
  row_pk: string;
  seq: Int8;
  session_id: string | null;
  table_name: string;
}

export interface AuthEvent {
  at: Generated<Timestamp>;
  counts_toward_lockout: boolean;
  detail: Generated<Json>;
  id: Generated<Int8>;
  kind: string;
  person_id: string | null;
  session_id: string | null;
  typed_user: string | null;
}

export interface Authorisation {
  id: string;
  lab_id: string;
  meaning: string;
  person_id: string;
  scope: string;
  suspended_at: Timestamp | null;
  valid_from: Timestamp;
  valid_until: Timestamp;
}

export interface Blob {
  ledger_id: string;
  media_type: string;
  sha256: Buffer;
  size_bytes: Int8;
  stored_at: Generated<Timestamp>;
}

export interface CommitOutcome {
  body: Json;
  command: string;
  commit_key: string;
  input_hash: Buffer;
  outcome: string;
  session_id: string | null;
  settled_at: Generated<Timestamp>;
}

export interface EffectiveVersion {
  app_release: string | null;
  content: Buffer | null;
  content_hash: Buffer | null;
  content_schema: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  ledger_id: string | null;
  record_id: string | null;
  requires_approval: boolean | null;
  version_no: number | null;
}

export interface EnrolmentLink {
  created_at: Generated<Timestamp>;
  created_by: string;
  expires_at: Timestamp;
  id: string;
  person_id: string;
  token_hash: Buffer;
  totp_secret_enc: Buffer | null;
  used_at: Timestamp | null;
  username: string;
}

export interface Lab {
  code: string;
  iana_zone: string;
  id: string;
}

export interface Ledger {
  code: string;
  id: string;
  kind: string;
}

export interface LockoutState {
  consecutive_failures: Int8 | null;
  locked_out: boolean | null;
  person_id: string | null;
}

export interface PendingVersion {
  app_release: string | null;
  content: Buffer | null;
  content_hash: Buffer | null;
  content_schema: string | null;
  created_at: Timestamp | null;
  created_by: string | null;
  id: string | null;
  ledger_id: string | null;
  record_id: string | null;
  requires_approval: boolean | null;
  version_no: number | null;
}

export interface Person {
  created_at: Generated<Timestamp>;
  id: string;
  native_name: string | null;
  printed_name: string;
}

export interface Record {
  created_at: Generated<Timestamp>;
  id: string;
  kind: string;
  ledger_id: string;
  parent_id: string | null;
}

export interface RecordedValue {
  critical: boolean;
  field: string;
  ledger_id: string;
  parent_id: string;
  record_id: string;
  subject: Generated<string>;
  unit: string | null;
  value_type: string;
}

export interface RecordedValueVersion {
  blob_hash: Buffer | null;
  decimals: number | null;
  ledger_id: string;
  value_text: string;
  version_id: string;
}

export interface RecordKind {
  approval_after_first_save: boolean;
  kind: string;
  ledger_class: string;
  meanings: string[];
}

export interface RecordLock {
  at: Generated<Timestamp>;
  ledger_id: string;
  record_id: string;
  signature_id: string;
}

export interface RecordVersion {
  app_release: string;
  content: Buffer;
  content_hash: Generated<Buffer>;
  content_schema: string;
  created_at: Generated<Timestamp>;
  created_by: string;
  id: string;
  ledger_id: string;
  record_id: string;
  requires_approval: Generated<boolean>;
  version_no: number;
}

export interface RecordVersionCite {
  cited_hash: Buffer;
  cited_version: string;
  ledger_id: string;
  version_id: string;
}

export interface Release {
  deployed_at: Generated<Timestamp>;
  id: string;
  image_digest: string | null;
}

export interface RoleGrant {
  customer_id: string | null;
  granted_at: Generated<Timestamp>;
  id: string;
  lab_id: string | null;
  person_id: string;
  revoked_at: Timestamp | null;
  role: string;
}

export interface Session {
  absolute_end_at: Timestamp;
  acting_lab_id: string | null;
  customer_id: string | null;
  end_reason: string | null;
  ended_at: Timestamp | null;
  id: string;
  lock_reason: string | null;
  locked_at: Timestamp | null;
  person_id: string;
  started_at: Generated<Timestamp>;
  token_hash: Buffer;
  workstation: string;
}

export interface SessionActivity {
  last_activity_at: Timestamp;
  session_id: string;
}

export interface Signature {
  app_release: string;
  attestation_hash: Buffer | null;
  attestation_version_id: string | null;
  authenticator: string;
  commit_key: string;
  content_hash: Buffer;
  group_id: string;
  id: string;
  ledger_id: string;
  meaning: string;
  printed_name: string;
  record_version_id: string;
  role: string;
  session_id: string;
  signed_at: Timestamp;
  signer_lab_id: string | null;
  signer_person_id: string;
  username: string;
}

export interface SpecGap {
  at: Generated<Timestamp>;
  command: string;
  detail: Json;
  feature: string;
  id: Generated<Int8>;
  person_id: string;
  record_id: string | null;
}

export interface TotpStepUsed {
  person_id: string;
  purpose: string;
  step: Int8;
  used_at: Generated<Timestamp>;
}

export interface TrainingRecord {
  document_version: string;
  id: string;
  level: string;
  person_id: string;
}

export interface VersionRejection {
  at: Generated<Timestamp>;
  ledger_id: string;
  reason_code: string;
  reason_text: string | null;
  rejected_by: string;
  version_id: string;
}

export interface DB {
  account: Account;
  alert: Alert;
  audit_chain_head: AuditChainHead;
  audit_entry: AuditEntry;
  auth_event: AuthEvent;
  authorisation: Authorisation;
  blob: Blob;
  commit_outcome: CommitOutcome;
  effective_version: EffectiveVersion;
  enrolment_link: EnrolmentLink;
  lab: Lab;
  ledger: Ledger;
  lockout_state: LockoutState;
  pending_version: PendingVersion;
  person: Person;
  record: Record;
  record_kind: RecordKind;
  record_lock: RecordLock;
  record_version: RecordVersion;
  record_version_cite: RecordVersionCite;
  recorded_value: RecordedValue;
  recorded_value_version: RecordedValueVersion;
  release: Release;
  role_grant: RoleGrant;
  session: Session;
  session_activity: SessionActivity;
  signature: Signature;
  spec_gap: SpecGap;
  totp_step_used: TotpStepUsed;
  training_record: TrainingRecord;
  version_rejection: VersionRejection;
}

