/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccessEventKind = "AbsoluteExpiry" | "AuthenticatorEnrolled" | "EnrolmentGrantIssued" | "IdleExpiry" | "LabSwitch" | "LabSwitchFailed" | "Lock" | "Lockout" | "PasswordChanged" | "PasswordSet" | "ReauthenticationFailed" | "SignInFailed" | "SignInSucceeded" | "SignOut" | "Takeover" | "Unlock" | "UnlockFailed";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type AuditExportFormat = "CSV" | "JSON";

export type DataClass = "fictional" | "real";

export type DemoException = "Anchoring" | "DemoLogin" | "FileVault" | "PlaintextAtCloudflare" | "TwoRole";

export type DocumentStatus = "Abandoned" | "Approved" | "Draft" | "Effective" | "InReview" | "Retired" | "Superseded";

export type DocumentType = "ExternalDocument" | "Form" | "Method" | "MethodProtocol" | "MethodReport" | "Policy" | "QualityManual" | "SOP" | "WorkInstruction" | "Worksheet";

export type EquipmentEventKind = "Cleaning" | "FirmwareChange" | "Maintenance" | "Note" | "Repair" | "SoftwareChange" | "Suspect";

export type FitnessStatus = "Expired" | "InUse" | "Quarantined" | "Retired" | "Suspended";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type ImpactAnswer = "No" | "Yes";

export type IncidentKind = "ChainVerifyFailure" | "Lockout" | "RepeatedSignInOnLockedAccount" | "SignInBurstFromAddress" | "SignInBurstOnUnknownUserId" | "UnexpectedFailure" | "UnraisableLogLine";

export type IncidentState = "Acknowledged" | "Closed" | "Open";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Meaning = "Acknowledged" | "Approved" | "Authored" | "Performed" | "Released" | "Reviewed" | "Verified";

export type ReleaseLogKind = "ConfigurationChange" | "HostMove" | "Release";

export type Role = "Admin" | "Analyst" | "Customer" | "LabManager" | "PlatformOperator" | "QA" | "Reviewer" | "SampleCustodian";

export type SignInFailure = "AccountLocked" | "AlreadyEnrolled" | "CodeAlreadyUsed" | "NoAuthenticator" | "NoCredential" | "NoEnrolmentGrant" | "NoLab" | "NoLabChosen" | "NoMembership" | "NotInWorkstationLab" | "OtherPersonSignedIn" | "OtherUserId" | "SessionEnded" | "UnknownUserId" | "WrongCode" | "WrongPassword" | "WrongPasswordOnLockedAccount" | "WrongUserId";

export type TestState = "Assigned" | "Ready" | "Reported" | "Requested" | "Reviewed" | "SubmittedForReview";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessEvent {
  at: Generated<Timestamp>;
  dataClass: Generated<DataClass>;
  failureReason: SignInFailure | null;
  id: Generated<string>;
  kind: AccessEventKind;
  previousSessionId: string | null;
  previousSessionLabId: string | null;
  roles: ArrayType<Role>;
  sessionId: string | null;
  sessionLabId: string | null;
  sourceAddress: string | null;
  subjectId: string | null;
  takenById: string | null;
  typedUserIdHmac: Buffer | null;
  typedUserIdLength: number | null;
  workstationId: string | null;
}

export interface AuditEntry {
  actor: string;
  at: Timestamp;
  chain: string;
  hash: Buffer;
  newRow: Json | null;
  oldRow: Json | null;
  op: string;
  prevHash: Buffer;
  reason: string;
  role: string;
  seq: Int8;
  tableName: string;
  transactionId: string | null;
}

export interface AuditExport {
  customerId: string;
  dataClass: Generated<DataClass>;
  dataSha256: Buffer;
  entryCount: number;
  format: AuditExportFormat;
  generatedAt: Generated<Timestamp>;
  id: Generated<string>;
  labId: string;
  pdfSha256: Buffer;
  requestedBy: string;
  requestedRole: Generated<Role>;
}

export interface Authenticator {
  enrolledAt: Generated<Timestamp>;
  lastUsedStep: Int8 | null;
  personId: string;
  secretCiphertext: Buffer;
}

export interface ChainVerification {
  chain: string;
  dataClass: Generated<DataClass>;
  head: Buffer;
  id: Generated<string>;
  recomputedFrom: Int8;
  through: Int8;
  verifiedAt: Generated<Timestamp>;
  verifiedBy: string;
}

export interface CommitKey {
  committedAt: Generated<Timestamp>;
  key: string;
  labId: string;
  requestHash: Buffer;
  sessionId: string;
  state: TestState;
  testId: string;
}

export interface CredentialLink {
  dataClass: Generated<DataClass>;
  expiresAt: Generated<Timestamp>;
  id: Generated<string>;
  issuedAt: Generated<Timestamp>;
  personId: string;
  tokenHash: Buffer;
  usedAt: Timestamp | null;
}

export interface Customer {
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  name: string;
}

export interface Deployment {
  dataClass: Generated<DataClass>;
  setByEntryId: string | null;
  single: Generated<boolean>;
}

export interface Document {
  createdAt: Generated<Timestamp>;
  dataClass: Generated<DataClass>;
  documentType: DocumentType;
  id: Generated<string>;
  labId: string;
  number: ColumnType<string, never, never>;
}

export interface DocumentVersion {
  abandonReason: string | null;
  authorId: string;
  body: string;
  dataClass: Generated<DataClass>;
  documentId: string;
  effectiveDate: Timestamp;
  id: Generated<string>;
  labId: string;
  savedAt: Generated<Timestamp>;
  status: Generated<DocumentStatus>;
  title: string;
  version: number;
}

export interface EnrolmentGrant {
  dataClass: Generated<DataClass>;
  expiresAt: Generated<Timestamp>;
  id: Generated<string>;
  issuedAt: Generated<Timestamp>;
  issuedBy: string;
  personId: string;
  tokenHash: Buffer;
  usedAt: Timestamp | null;
}

export interface Equipment {
  assetNumber: string | null;
  dataClass: Generated<DataClass>;
  firmwareVersion: string | null;
  fitnessStatus: Generated<FitnessStatus>;
  id: Generated<string>;
  kind: string;
  labId: string;
  manufacturer: string;
  model: string;
  name: string;
  registeredAt: Generated<Timestamp>;
  responsiblePersonId: string;
  roomId: string;
  serial: string;
  softwareVersion: string | null;
}

export interface EquipmentEvent {
  dataClass: Generated<DataClass>;
  equipmentId: string;
  id: Generated<string>;
  kind: EquipmentEventKind;
  labId: string;
  note: string;
  recordedAt: Generated<Timestamp>;
  recordedBy: string;
}

export interface IdentityVerification {
  checkedAt: Generated<Timestamp>;
  checkedBy: string;
  checkedInLabId: string;
  dataClass: Generated<DataClass>;
  evidence: string;
  id: Generated<string>;
  printedName: string;
}

export interface IncidentBreak {
  fingerprint: Buffer;
  incidentId: string;
  kind: string;
  seq: Int8;
  through: Int8;
}

export interface Lab {
  code: string;
  dataClass: Generated<DataClass>;
  labId: Generated<string>;
  name: string;
  timeZone: string;
}

export interface Membership {
  dataClass: Generated<DataClass>;
  labId: string;
  personId: string;
  role: Role;
}

export interface Method {
  code: string;
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  title: string;
  version: string;
}

export interface Person {
  customerId: string | null;
  dataClass: Generated<DataClass>;
  displayName: string;
  failedLogins: Generated<number>;
  id: Generated<string>;
  identityVerificationId: string | null;
  lockedAt: Timestamp | null;
  passwordHash: string | null;
  reducedMotion: Generated<boolean>;
  username: string;
}

export interface Reauthentication {
  at: Generated<Timestamp>;
  authenticator: string;
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  labId: string;
  meaning: Meaning;
  personId: string;
  sessionId: string;
}

export interface RecordVersion {
  canonicalForm: number;
  content: Buffer;
  contentHash: Generated<Buffer>;
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  labId: string | null;
  recordId: string;
  recordTable: string;
  savedAt: Generated<Timestamp>;
  version: number;
}

export interface ReleaseLogEntry {
  ciResult: string | null;
  ciRun: string | null;
  dataClass: Generated<DataClass>;
  fileVaultPersonalKey: boolean | null;
  id: Generated<string>;
  imageDigests: string[] | null;
  kind: ReleaseLogKind;
  lapsesExceptions: Generated<ArrayType<DemoException>>;
  recordedAt: Generated<Timestamp>;
  recordsExceptions: Generated<ArrayType<DemoException>>;
  release: string | null;
  setsDataClass: DataClass | null;
  statement: Buffer | null;
  statementVersion: number | null;
  summary: string;
  title: string;
  zapBaselineResult: string | null;
}

export interface Result {
  analyte: string;
  dataClass: Generated<DataClass>;
  enteredBy: string;
  id: Generated<string>;
  injectionSequenceRef: string;
  labId: string;
  notebookRef: string;
  performedOn: Timestamp;
  testId: string;
  unit: string;
  value: string;
}

export interface Room {
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  labId: string;
  name: string;
}

export interface Sample {
  dataClass: Generated<DataClass>;
  description: string;
  id: Generated<string>;
  labId: string;
  number: string;
  receivedAt: Timestamp | null;
  receivedTimeZone: ColumnType<string | null, never, never>;
  submissionId: string;
}

export interface ServiceIdentity {
  createdByEntryId: string;
  dataClass: Generated<DataClass>;
  name: string;
  retiredByEntryId: string | null;
  scope: string[];
}

export interface Session {
  createdAt: Generated<Timestamp>;
  endedAt: Timestamp | null;
  id: Generated<string>;
  labId: string;
  lastSeenAt: Generated<Timestamp>;
  lockedAt: Timestamp | null;
  personId: string;
  tokenHash: Buffer;
  workstationId: string | null;
}

export interface Signature {
  appRelease: string | null;
  authenticator: string | null;
  canonicalForm: number;
  contentHash: Buffer;
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  labId: string;
  meaning: Meaning;
  personId: string;
  printedName: ColumnType<string, never, never>;
  reauthenticationId: string | null;
  recordVersionId: string;
  role: Role;
  sessionId: string | null;
  signedAt: Generated<Timestamp>;
  signedTimeZone: ColumnType<string, never, never>;
  statementHash: Buffer | null;
  statementVersion: number | null;
  username: ColumnType<string, never, never>;
}

export interface SignatureStatement {
  approvedAt: Generated<Timestamp>;
  dataClass: Generated<DataClass>;
  statement: Buffer;
  statementHash: Generated<Buffer>;
  version: number;
}

export interface SigningRole {
  dataClass: Generated<DataClass>;
  meaning: Meaning;
  role: Role;
}

export interface Submission {
  customerId: string;
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  number: string;
  submittedBy: string;
}

export interface SystemIncident {
  breakCount: number | null;
  chain: string | null;
  constraintName: string | null;
  correctiveAction: string | null;
  correctiveActionAt: Timestamp | null;
  correctiveActionBy: string | null;
  dataClass: Generated<DataClass>;
  errorClass: string | null;
  fingerprint: Buffer | null;
  firstFailure: Int8 | null;
  id: Generated<string>;
  immediateAction: string | null;
  immediateActionAt: Timestamp | null;
  immediateActionBy: string | null;
  impactAnswer: ImpactAnswer | null;
  impactAnsweredAt: Timestamp | null;
  impactAnsweredBy: string | null;
  kind: IncidentKind;
  lastFailure: Int8 | null;
  loggedAt: Timestamp | null;
  openedAt: Generated<Timestamp>;
  recordId: string | null;
  reference: string;
  requestedBy: string | null;
  sessionLabId: string | null;
  sourceAddress: string | null;
  sqlstate: string | null;
  state: Generated<IncidentState>;
  step: string | null;
  subjectId: string | null;
  typedUserIdHmac: Buffer | null;
}

export interface Test {
  assigneeId: string | null;
  dataClass: Generated<DataClass>;
  gxpClass: Generated<string>;
  id: Generated<string>;
  labId: string;
  methodId: string;
  sampleId: string;
  state: Generated<TestState>;
}

export interface TestReport {
  dataClass: Generated<DataClass>;
  id: Generated<string>;
  labId: string;
  number: string;
  testId: string;
}

export interface TrainingRecord {
  dataClass: Generated<DataClass>;
  labId: string;
  methodId: string;
  personId: string;
}

export interface Workstation {
  browserPolicy: string;
  dataClass: Generated<DataClass>;
  deviceTokenHash: Buffer | null;
  id: Generated<string>;
  labId: string;
  name: string;
  roomId: string;
}

export interface DB {
  accessEvent: AccessEvent;
  auditEntry: AuditEntry;
  auditExport: AuditExport;
  authenticator: Authenticator;
  chainVerification: ChainVerification;
  commitKey: CommitKey;
  credentialLink: CredentialLink;
  customer: Customer;
  deployment: Deployment;
  document: Document;
  documentVersion: DocumentVersion;
  enrolmentGrant: EnrolmentGrant;
  equipment: Equipment;
  equipmentEvent: EquipmentEvent;
  identityVerification: IdentityVerification;
  incidentBreak: IncidentBreak;
  lab: Lab;
  membership: Membership;
  method: Method;
  person: Person;
  reauthentication: Reauthentication;
  recordVersion: RecordVersion;
  releaseLogEntry: ReleaseLogEntry;
  result: Result;
  room: Room;
  sample: Sample;
  serviceIdentity: ServiceIdentity;
  session: Session;
  signature: Signature;
  signatureStatement: SignatureStatement;
  signingRole: SigningRole;
  submission: Submission;
  systemIncident: SystemIncident;
  test: Test;
  testReport: TestReport;
  trainingRecord: TrainingRecord;
  workstation: Workstation;
}
