/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type AccessEventKind = "AbsoluteExpiry" | "IdleExpiry" | "LabSwitch" | "LabSwitchFailed" | "Lock" | "Lockout" | "PasswordSet" | "ReauthenticationFailed" | "SignInFailed" | "SignInSucceeded" | "SignOut" | "Takeover" | "Unlock" | "UnlockFailed";

export type ArrayType<T> = ArrayTypeImpl<T> extends (infer U)[]
  ? U[]
  : ArrayTypeImpl<T>;

export type ArrayTypeImpl<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S[], I[], U[]>
  : T[];

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type IncidentKind = "Lockout" | "RepeatedSignInOnLockedAccount" | "SignInBurstFromAddress" | "SignInBurstOnUnknownUserId" | "UnexpectedFailure" | "UnraisableLogLine";

export type IncidentState = "Open";

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Meaning = "Acknowledged" | "Approved" | "Authored" | "Performed" | "Released" | "Reviewed" | "Verified";

export type Role = "Admin" | "Analyst" | "Customer" | "LabManager" | "PlatformOperator" | "QA" | "Reviewer" | "SampleCustodian";

export type SignInFailure = "AccountLocked" | "NoCredential" | "NoLab" | "NoLabChosen" | "NoMembership" | "NotInWorkstationLab" | "OtherUserId" | "SessionEnded" | "UnknownUserId" | "WrongPassword" | "WrongPasswordOnLockedAccount" | "WrongUserId";

export type TestState = "Assigned" | "Ready" | "Reported" | "Requested" | "Reviewed" | "SubmittedForReview";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AccessEvent {
  at: Generated<Timestamp>;
  failureReason: SignInFailure | null;
  id: Generated<string>;
  kind: AccessEventKind;
  previousSessionId: string | null;
  previousSessionLabId: string | null;
  roles: ArrayType<Role>;
  sessionId: string | null;
  sessionLabId: string | null;
  sourceAddress: string | null;
  subjectId: string | null;
  takenById: string | null;
  typedUserIdHmac: Buffer | null;
  typedUserIdLength: number | null;
  workstationId: string | null;
}

export interface AuditEntry {
  actor: string;
  at: Timestamp;
  chain: string;
  hash: Buffer;
  newRow: Json | null;
  oldRow: Json | null;
  op: string;
  prevHash: Buffer;
  reason: string;
  role: string;
  seq: Int8;
  tableName: string;
  transactionId: string | null;
}

export interface CommitKey {
  committedAt: Generated<Timestamp>;
  key: string;
  labId: string;
  requestHash: Buffer;
  sessionId: string;
  state: TestState;
  testId: string;
}

export interface CredentialLink {
  expiresAt: Generated<Timestamp>;
  id: Generated<string>;
  issuedAt: Generated<Timestamp>;
  personId: string;
  tokenHash: Buffer;
  usedAt: Timestamp | null;
}

export interface Customer {
  id: Generated<string>;
  name: string;
}

export interface IdentityVerification {
  checkedAt: Generated<Timestamp>;
  checkedBy: string;
  checkedInLabId: string;
  evidence: string;
  id: Generated<string>;
  printedName: string;
}

export interface Lab {
  code: string;
  labId: Generated<string>;
  name: string;
  timeZone: string;
}

export interface Membership {
  labId: string;
  personId: string;
  role: Role;
}

export interface Method {
  code: string;
  id: Generated<string>;
  title: string;
  version: string;
}

export interface Person {
  customerId: string | null;
  displayName: string;
  failedLogins: Generated<number>;
  id: Generated<string>;
  identityVerificationId: string | null;
  lockedAt: Timestamp | null;
  passwordHash: string | null;
  username: string;
}

export interface Reauthentication {
  at: Generated<Timestamp>;
  authenticator: string;
  id: Generated<string>;
  labId: string;
  meaning: Meaning;
  personId: string;
  sessionId: string;
}

export interface RecordVersion {
  canonicalForm: number;
  content: Buffer;
  contentHash: Generated<Buffer>;
  id: Generated<string>;
  labId: string;
  recordId: string;
  recordTable: string;
  savedAt: Generated<Timestamp>;
  version: number;
}

export interface Result {
  analyte: string;
  enteredBy: string;
  id: Generated<string>;
  injectionSequenceRef: string;
  labId: string;
  notebookRef: string;
  performedOn: Timestamp;
  testId: string;
  unit: string;
  value: string;
}

export interface Room {
  id: Generated<string>;
  labId: string;
  name: string;
}

export interface Sample {
  description: string;
  id: Generated<string>;
  labId: string;
  number: string;
  receivedAt: Timestamp | null;
  submissionId: string;
}

export interface Session {
  createdAt: Generated<Timestamp>;
  endedAt: Timestamp | null;
  id: Generated<string>;
  labId: string;
  lastSeenAt: Generated<Timestamp>;
  lockedAt: Timestamp | null;
  personId: string;
  tokenHash: Buffer;
  workstationId: string | null;
}

export interface Signature {
  appRelease: string | null;
  authenticator: string | null;
  canonicalForm: number;
  contentHash: Buffer;
  id: Generated<string>;
  labId: string;
  meaning: Meaning;
  personId: string;
  printedName: ColumnType<string, never, never>;
  reauthenticationId: string | null;
  recordVersionId: string;
  role: Role;
  sessionId: string | null;
  signedAt: Generated<Timestamp>;
  statementHash: Buffer | null;
  statementVersion: number | null;
  username: ColumnType<string, never, never>;
}

export interface SignatureStatement {
  approvedAt: Generated<Timestamp>;
  statement: Buffer;
  statementHash: Generated<Buffer>;
  version: number;
}

export interface Submission {
  customerId: string;
  id: Generated<string>;
  number: string;
  submittedBy: string;
}

export interface SystemIncident {
  constraintName: string | null;
  errorClass: string | null;
  id: Generated<string>;
  kind: IncidentKind;
  loggedAt: Timestamp | null;
  openedAt: Generated<Timestamp>;
  recordId: string | null;
  reference: string;
  requestedBy: string | null;
  sessionLabId: string | null;
  sourceAddress: string | null;
  sqlstate: string | null;
  state: Generated<IncidentState>;
  step: string | null;
  subjectId: string | null;
  typedUserIdHmac: Buffer | null;
}

export interface Test {
  assigneeId: string | null;
  gxpClass: Generated<string>;
  id: Generated<string>;
  labId: string;
  methodId: string;
  sampleId: string;
  state: Generated<TestState>;
}

export interface TestReport {
  id: Generated<string>;
  labId: string;
  number: string;
  testId: string;
}

export interface TrainingRecord {
  labId: string;
  methodId: string;
  personId: string;
}

export interface Workstation {
  browserPolicy: string;
  deviceTokenHash: Buffer | null;
  id: Generated<string>;
  labId: string;
  name: string;
  roomId: string;
}

export interface DB {
  accessEvent: AccessEvent;
  auditEntry: AuditEntry;
  commitKey: CommitKey;
  credentialLink: CredentialLink;
  customer: Customer;
  identityVerification: IdentityVerification;
  lab: Lab;
  membership: Membership;
  method: Method;
  person: Person;
  reauthentication: Reauthentication;
  recordVersion: RecordVersion;
  result: Result;
  room: Room;
  sample: Sample;
  session: Session;
  signature: Signature;
  signatureStatement: SignatureStatement;
  submission: Submission;
  systemIncident: SystemIncident;
  test: Test;
  testReport: TestReport;
  trainingRecord: TrainingRecord;
  workstation: Workstation;
}
