/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Meaning = "Acknowledged" | "Approved" | "Authored" | "Performed" | "Released" | "Reviewed" | "Verified";

export type Numeric = ColumnType<string, number | string, number | string>;

export type Role = "Admin" | "Analyst" | "Customer" | "LabManager" | "QA" | "Reviewer" | "SampleCustodian";

export type TestState = "Assigned" | "Ready" | "Reported" | "Requested" | "Reviewed" | "SubmittedForReview";

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface AuditEntry {
  actor: string;
  at: Timestamp;
  chain: string;
  hash: Buffer;
  new_row: Json | null;
  old_row: Json | null;
  op: string;
  prev_hash: Buffer;
  reason: string;
  role: string;
  seq: Int8;
  table_name: string;
}

export interface Customer {
  id: Generated<string>;
  name: string;
}

export interface Lab {
  code: string;
  lab_id: Generated<string>;
  name: string;
}

export interface Membership {
  lab_id: string;
  person_id: string;
  role: Role;
}

export interface Method {
  code: string;
  id: Generated<string>;
  title: string;
  version: string;
}

export interface Person {
  customer_id: string | null;
  display_name: string;
  failed_logins: Generated<number>;
  id: Generated<string>;
  locked_at: Timestamp | null;
  password_hash: string;
  username: string;
}

export interface Result {
  analyte: string;
  entered_by: string;
  id: Generated<string>;
  injection_sequence_ref: string;
  lab_id: string;
  notebook_ref: string;
  performed_on: Timestamp;
  test_id: string;
  unit: string;
  value: Numeric;
}

export interface Sample {
  description: string;
  id: Generated<string>;
  lab_id: string;
  number: string;
  received_at: Timestamp | null;
  submission_id: string;
}

export interface Session {
  created_at: Generated<Timestamp>;
  ended_at: Timestamp | null;
  id: Generated<string>;
  lab_id: string;
  last_seen_at: Generated<Timestamp>;
  person_id: string;
  token_hash: Buffer;
}

export interface Signature {
  content: Buffer;
  content_hash: Generated<Buffer>;
  id: Generated<string>;
  lab_id: string;
  meaning: Meaning;
  person_id: string;
  record_id: string;
  record_table: string;
  signed_at: Generated<Timestamp>;
}

export interface Submission {
  customer_id: string;
  id: Generated<string>;
  submitted_by: string;
}

export interface Test {
  assignee_id: string | null;
  gxp_class: Generated<string>;
  id: Generated<string>;
  lab_id: string;
  method_id: string;
  sample_id: string;
  state: Generated<TestState>;
}

export interface TestReport {
  id: Generated<string>;
  lab_id: string;
  number: string;
  test_id: string;
}

export interface TrainingRecord {
  lab_id: string;
  method_id: string;
  person_id: string;
}

export interface DB {
  audit_entry: AuditEntry;
  customer: Customer;
  lab: Lab;
  membership: Membership;
  method: Method;
  person: Person;
  result: Result;
  sample: Sample;
  session: Session;
  signature: Signature;
  submission: Submission;
  test: Test;
  test_report: TestReport;
  training_record: TrainingRecord;
}
