// Generated by scripts/codegen.ts from the migrated database. Do not edit.
export const LAB_TABLES = ['authorisation'] as const;
export const LEDGER_TABLES = ['audit_chain_head', 'audit_entry', 'blob', 'effective_version', 'pending_version', 'record', 'record_lock', 'record_version', 'record_version_cite', 'recorded_value', 'recorded_value_version', 'signature', 'version_rejection'] as const;
export const PORTAL_VIEWS = [] as const;
export const COMPANY_TABLES = ['account', 'alert', 'auth_event', 'commit_outcome', 'enrolment_link', 'lab', 'ledger', 'lockout_state', 'person', 'record_kind', 'release', 'role_grant', 'session', 'session_activity', 'spec_gap', 'totp_step_used', 'training_record'] as const;
export const INSERT_ONLY_TABLES = ['alert', 'audit_entry', 'auth_event', 'blob', 'record', 'record_lock', 'record_version', 'record_version_cite', 'recorded_value', 'recorded_value_version', 'release', 'signature', 'spec_gap', 'totp_step_used', 'version_rejection'] as const;
export const DOOR_ONLY_TABLES = ['audit_chain_head', 'audit_entry', 'ledger', 'record_kind', 'record_lock', 'record_version', 'record_version_cite', 'signature'] as const;

export type LabTable = (typeof LAB_TABLES)[number];
export type LedgerTable = (typeof LEDGER_TABLES)[number];
export type PortalView = (typeof PORTAL_VIEWS)[number];
export type CompanyTable = (typeof COMPANY_TABLES)[number];
