import { createHash, randomUUID } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { expect, type Locator, type Page, test } from '@playwright/test';
import { DEMO_PASSWORD } from '../playwright.config.ts';

async function signIn(page: Page, username: string) {
  await page.getByLabel('Username').fill(username);
  await page.getByLabel('Password').fill(DEMO_PASSWORD);
  await page.getByRole('button', { name: 'Sign in' }).click();
  await expect(page.getByRole('heading', { name: 'Tests' })).toBeVisible();
}

async function atLeast(target: Locator, width: number, height: number) {
  const b = await target.boundingBox();
  if (!b) throw new Error('the element is not on screen');
  expect(b.width + 0.01, 'touch target width').toBeGreaterThanOrEqual(width);
  expect(b.height + 0.01, 'touch target height').toBeGreaterThanOrEqual(height);
}

test('QA picks a Customer, generates its Audit Export and downloads the data file and the PDF', async ({ page }) => {
  await page.goto('/');
  const login = await page.request.post('/api/login', { data: { username: 'cora.customer', password: DEMO_PASSWORD } });
  expect(login.ok()).toBe(true);
  const { methods } = await (await page.request.get('/api/lookups')).json();
  const description = `Metformin HCl 500 mg tablets (fictional, ${test.info().project.name} ${randomUUID()})`;
  const submit = await page.request.post('/api/steps/submit', {
    data: { commitKey: randomUUID(), input: { methodId: methods[0].id, description } },
  });
  expect(submit.ok(), await submit.text()).toBe(true);
  await page.request.post('/api/logout', { data: {} });
  await page.reload();

  await signIn(page, 'rui.reviewer');
  await page.goto('/#/audit-export');
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Audit Export');
  await expect(page.getByText('an Audit Export is generated by QA')).toBeVisible();
  await page.getByRole('button', { name: 'Sign out' }).click();

  await signIn(page, 'quinn.qa');
  await page.getByRole('link', { name: 'Audit Export' }).click();
  await expect(page.getByRole('heading', { level: 1 })).toHaveText('Audit Export');
  const customer = page.getByLabel('Customer');
  const format = page.getByLabel('Data file');
  const generate = page.getByRole('button', { name: 'Generate export' });
  for (const control of [customer, format, generate]) await atLeast(control, 44, 44);
  await customer.selectOption({ label: 'Northwind Generics (fictional)' });
  await format.selectOption('CSV');
  await generate.click();

  const done = page.getByRole('region', { name: 'Generated export' });
  await expect(done.getByRole('heading')).toHaveText('For Northwind Generics (fictional)');
  await expect(done).toContainText(/Generated \d{4}-\d\d-\d\d \d\d:\d\d:\d\d UTC: \d+ entries\./);
  const links = done.getByRole('link');
  await expect(links).toHaveCount(2);
  for (const [i, ext] of [
    [0, 'csv'],
    [1, 'pdf'],
  ] as const) {
    const link = links.nth(i);
    await atLeast(link, 44, 44);
    const [download] = await Promise.all([page.waitForEvent('download'), link.click()]);
    expect(download.suggestedFilename()).toMatch(
      new RegExp(`^audit-export-northwind-generics-fictional-\\d{4}-\\d\\d-\\d\\d\\.${ext}$`),
    );
    const bytes = await readFile(await download.path());
    const shown = await done.getByRole('listitem').nth(i).locator('code').textContent();
    expect(shown).toBe(`SHA-256 ${createHash('sha256').update(bytes).digest('hex')}`);
    if (ext === 'csv') expect(bytes.toString('utf8')).toContain(description);
    else expect(bytes.subarray(0, 8).toString('latin1')).toBe('%PDF-1.4');
  }
});
