import { createHash } from 'node:crypto';
import type { DB } from '@lims/db';
import {
  type AuditExportData,
  type AuditExportFormat,
  chainVerification,
  describeTrail,
  type ExportedEntry,
  type Instant,
  redactionFor,
  routes,
  type ShownValue,
} from '@lims/domain';
import { type Kysely, sql } from 'kysely';
import type { App } from './app.ts';
import { PDF_COLUMNS, textPdf } from './pdf.ts';
import { refuse } from './refuse.ts';
import { labScope, type Scope } from './scope.ts';
import { imagesFor, rawEntries } from './trail.ts';

const rowId = sql<string>`coalesce(new_row, old_row)->>'id'`;

function qaScope(db: Kysely<DB>, req: { actor: Scope['ctx'] }): Scope {
  if (!req.actor.roles.includes('QA')) refuse('role', 'an Audit Export is generated by QA');
  return labScope(db, req.actor);
}

const customersSeen = (scope: Scope) =>
  scope.company
    .selectFrom('customer')
    .select(['id', 'name'])
    .where(
      'id',
      'in',
      scope
        .from('sample')
        .innerJoin('submission', 'submission.id', 'sample.submissionId')
        .select('submission.customerId'),
    )
    .orderBy('name');

interface CustomerRecords {
  labIds: string[];
  submissionIds: Set<string>;
  methodIds: Set<string>;
  names: string[];
}

/**
 * Every record of this Lab and the company that belongs to one Customer, keyed by that Customer: the ids of its Lab
 * records, the Submissions and Methods its Samples reach, and every identifier that names it or one of its records.
 */
async function recordsByCustomer(scope: Scope) {
  const [samples, tests, results, reports, versions, signatures, customers, submissions, users] = await Promise.all([
    scope
      .from('sample')
      .innerJoin('submission', 'submission.id', 'sample.submissionId')
      .select(['sample.id', 'sample.number', 'sample.submissionId', 'submission.customerId'])
      .execute(),
    scope.from('test').select(['id', 'sampleId', 'methodId']).execute(),
    scope.from('result').select(['id', 'testId']).execute(),
    scope.from('testReport').select(['id', 'number', 'testId']).execute(),
    scope.from('recordVersion').select(['id', 'recordId']).execute(),
    scope.from('signature').select(['id', 'recordVersionId']).execute(),
    scope.company.selectFrom('customer').select(['id', 'name']).execute(),
    scope.company.selectFrom('submission').select(['id', 'number', 'customerId']).execute(),
    scope.company
      .selectFrom('person')
      .select(['id', 'username', 'displayName', 'customerId'])
      .where('customerId', 'is not', null)
      .execute(),
  ]);
  const of = new Map<string, CustomerRecords>(
    customers.map((c) => [c.id, { labIds: [], submissionIds: new Set(), methodIds: new Set(), names: [c.id, c.name] }]),
  );
  const owner = new Map<string, string>();
  const own = (id: string, by: string | undefined, ...names: string[]) => {
    const customer = by === undefined ? undefined : of.get(by);
    if (by === undefined || !customer) return;
    owner.set(id, by);
    customer.labIds.push(id);
    customer.names.push(id, ...names);
  };
  for (const s of samples) {
    own(s.id, s.customerId, s.number);
    of.get(s.customerId)?.submissionIds.add(s.submissionId);
  }
  for (const t of tests) {
    own(t.id, owner.get(t.sampleId));
    const customer = owner.get(t.id);
    if (customer) of.get(customer)?.methodIds.add(t.methodId);
  }
  for (const r of results) own(r.id, owner.get(r.testId));
  for (const r of reports) own(r.id, owner.get(r.testId), r.number);
  for (const v of versions) own(v.id, owner.get(v.recordId));
  for (const s of signatures) own(s.id, owner.get(s.recordVersionId));
  for (const s of submissions) of.get(s.customerId)?.names.push(s.id, s.number);
  for (const u of users) if (u.customerId) of.get(u.customerId)?.names.push(u.id, u.username, u.displayName);
  return of;
}

const sha256 = (bytes: Buffer) => createHash('sha256').update(bytes).digest('hex');
const shownText = (value: ShownValue | null) => value?.text ?? '';
const rawText = (value: unknown) =>
  value === undefined || value === null ? '' : typeof value === 'string' ? value : JSON.stringify(value);
const chainWords = { lab: 'Lab chain', company: 'Company chain' } as const;

function csvField(value: string): string {
  return /[",\r\n]/.test(value) ? `"${value.replaceAll('"', '""')}"` : value;
}

const CSV_HEADER = [
  'Chain',
  'Entry',
  'Time (UTC)',
  "Time (Lab's zone)",
  'Actor',
  'Role',
  'Action',
  'Record kind',
  'Record',
  'Record ID',
  'Field',
  'Field name',
  'Old value',
  'New value',
  'Old raw value',
  'New raw value',
  'Reason',
  'Transaction',
  'Redacted',
  'Hash',
  'Previous hash',
];

/** One CSV row per changed field, or one row for an entry that changed none, so the file sorts and filters in a spreadsheet. */
function csvOf(data: AuditExportData): string {
  const rows = data.entries.flatMap((e) => {
    const base = (field: string, label: string, old: string, now: string, oldRaw: string, newRaw: string) => [
      chainWords[e.chain],
      e.seq,
      e.at,
      e.atLab ?? '',
      e.actor.label,
      e.actor.role,
      e.op,
      e.record.kind,
      e.record.label,
      e.record.id,
      field,
      label,
      old,
      now,
      oldRaw,
      newRaw,
      e.reason,
      e.raw.transactionId ?? '',
      e.redacted ? 'yes' : 'no',
      e.raw.hash,
      e.raw.prevHash,
    ];
    if (e.changes.length === 0) return [base('', '', '', '', '', '')];
    return e.changes.map((c) =>
      base(
        c.field,
        c.label,
        shownText(c.old),
        shownText(c.new),
        rawText(e.raw.oldRow?.[c.field]),
        rawText(e.raw.newRow?.[c.field]),
      ),
    );
  });
  return `${[CSV_HEADER, ...rows].map((row) => row.map((field) => csvField(field)).join(',')).join('\r\n')}\r\n`;
}

function entryLines(e: ExportedEntry): string[] {
  const indent = (text: string) => `    ${text}`;
  return [
    `${chainWords[e.chain]} entry ${e.seq}  ${e.at}${e.atLab ? `  (Lab: ${e.atLab})` : ''}`,
    indent(`${e.actor.label} (${e.actor.role}) ${e.op} ${e.record.kind} ${e.record.label} [${e.record.id}]`),
    indent(`Reason: ${e.reason}`),
    ...e.changes.map((c) => indent(`${c.label}: ${shownText(c.old) || '(none)'} -> ${shownText(c.new) || '(none)'}`)),
    ...(e.redacted
      ? [indent(`Redacted: another Customer's identifier is replaced, so the raw row differs from the hashed one.`)]
      : []),
    indent(`Hash ${e.raw.hash}`),
    '',
  ];
}

function pdfOf(data: AuditExportData, dataFile: { name: string; sha256: string }): Buffer {
  const title = `Audit Export for ${data.customer.name}`;
  const lines = [
    title,
    '='.repeat(Math.min(title.length, PDF_COLUMNS)),
    `Lab: ${data.lab.name} (${data.lab.code}), zone ${data.lab.zone}`,
    `As of: ${data.asOf} UTC`,
    `Generated by: ${data.generatedBy.label} (${data.generatedBy.username}), ${data.generatedBy.role}`,
    ...data.chains.map((c) => `${chainWords[c.chain]}: ${c.report}`),
    `Entries: ${data.entries.length}, of which redacted: ${data.entries.filter((e) => e.redacted).length}`,
    `Data file: ${dataFile.name}`,
    `SHA-256 of the data file: ${dataFile.sha256}`,
    'The data file holds every entry with its raw values. Another Customer\'s identifiers read "[redacted]".',
    '',
    ...data.entries.flatMap((e) => entryLines(e)),
  ];
  return textPdf(title, lines);
}

const fileStem = (name: string, asOf: Instant) =>
  `audit-export-${
    name
      .normalize('NFKD')
      .replace(/[^A-Za-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .toLowerCase() || 'customer'
  }-${asOf.slice(0, 10)}`;

/** Registers the Audit Export routes: QA lists the Customers of this Lab and generates one Customer's redacted export, recorded on the Lab chain. */
export function auditExportRoutes(app: App, db: Kysely<DB>): void {
  app.route({
    ...routes.auditExportCustomers,
    handler: async (req) => customersSeen(qaScope(db, req)).execute(),
  });

  app.route({
    ...routes.auditExport,
    handler: async (req) => {
      const scope = qaScope(db, req);
      const { customerId, format } = req.body;
      const customer =
        (await customersSeen(scope).where('id', '=', customerId).executeTakeFirst()) ??
        refuse('notFound', 'no such Customer in this Lab');
      const labId = scope.ctx.lab.id;
      const byCustomer = await recordsByCustomer(scope);
      const mine = byCustomer.get(customer.id) ?? refuse('notFound', 'no such Customer in this Lab');
      const others = [...byCustomer].flatMap(([id, c]) => (id === customer.id ? [] : c.names));
      const { asOf } = await scope.company
        .selectNoFrom(sql<Instant>`to_char(now() at time zone 'UTC', 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"')`.as('asOf'))
        .executeTakeFirstOrThrow();
      const entries = await rawEntries(scope, (eb) =>
        eb.or([
          eb.and([
            eb('chain', '=', labId),
            eb.or([
              eb(rowId, '=', sql<string>`any(${mine.labIds}::text[])`),
              eb.and([eb('tableName', '=', 'audit_export'), eb(sql`new_row->>'customer_id'`, '=', customer.id)]),
            ]),
          ]),
          eb.and([
            eb('chain', '=', 'company'),
            eb.or([
              eb.and([eb('tableName', '=', 'customer'), eb(rowId, '=', customer.id)]),
              eb.and([
                eb('tableName', '=', 'submission'),
                eb(rowId, '=', sql<string>`any(${[...mine.submissionIds]}::text[])`),
              ]),
              eb.and([
                eb('tableName', '=', 'method'),
                eb(rowId, '=', sql<string>`any(${[...mine.methodIds]}::text[])`),
              ]),
            ]),
          ]),
        ]),
      );
      const [images, verified, lab] = await Promise.all([
        imagesFor(scope, entries),
        scope.verifyAuditTrail(),
        scope.company
          .selectFrom('lab')
          .select(['code', 'name', 'timeZone'])
          .where('labId', '=', labId)
          .executeTakeFirstOrThrow(),
      ]);
      const redact = redactionFor(mine.names, others);
      const data: AuditExportData = {
        customer,
        lab: { code: lab.code, name: lab.name, zone: lab.timeZone },
        asOf,
        generatedBy: { label: scope.ctx.person.displayName, username: scope.ctx.person.username, role: 'QA' },
        chains: verified.chains.map((c) => chainVerification(c.chain, c.lastEntry, c.firstFailure)),
        entries: describeTrail(entries, images, labId).map((e) => redact(e)),
      };
      const stem = fileStem(customer.name, asOf);
      const formats: Record<AuditExportFormat, { name: string; mediaType: string; bytes: Buffer }> = {
        JSON: {
          name: `${stem}.json`,
          mediaType: 'application/json',
          bytes: Buffer.from(JSON.stringify(data, null, 2)),
        },
        CSV: { name: `${stem}.csv`, mediaType: 'text/csv', bytes: Buffer.from(csvOf(data)) },
      };
      const dataFile = { ...formats[format], sha256: sha256(formats[format].bytes) };
      const pdf = pdfOf(data, dataFile);
      const pdfSha256 = sha256(pdf);
      const saved = await scope.write('generateAuditExport', 'QA', (q) =>
        q
          .insert('auditExport', {
            customerId: customer.id,
            requestedBy: scope.ctx.person.id,
            format,
            entryCount: data.entries.length,
            dataSha256: Buffer.from(dataFile.sha256, 'hex'),
            pdfSha256: Buffer.from(pdfSha256, 'hex'),
          })
          .returning(['id', 'generatedAt'])
          .executeTakeFirstOrThrow(),
      );
      return {
        id: saved.id,
        customer,
        generatedAt: saved.generatedAt,
        entryCount: data.entries.length,
        files: [
          {
            name: dataFile.name,
            mediaType: dataFile.mediaType,
            sha256: dataFile.sha256,
            base64: dataFile.bytes.toString('base64'),
          },
          { name: `${stem}.pdf`, mediaType: 'application/pdf', sha256: pdfSha256, base64: pdf.toString('base64') },
        ],
      };
    },
  });
}
